routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

//Route::get('/articles', 'ArticlesController@index')->name('articles.index');
//Route::get('/articles/{slug}', 'ArticlesController@single')->name('articles.single');
//Route::get('/articles/create', 'ArticlesController@create')->name('articles.create');

Route::resource('articles', 'ArticlesController');

Route::post('/comments', 'CommentController@store')->name('comments.store');


Route::get('/users', 'UsersController@index')->name('users.index');
Route::get('/users/{id}', 'UsersController@getSingleUser')->name('users.single');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/profile', 'UsersController@profile')->name('users.profile');

Route::post('/subscribe', 'UsersController@subscribe')->name('subscribe');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'confirmation_code', 'confirmed'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getName()
    {
        return $this->name;
    }

    public function articles()
    {
        return $this->hasMany('App\Article', 'user_id');
    }

    /**
     * Check if user has confirmed his account with email
     *
     * @return bool
     */
    public function isConfirmed()
    {
        return $this->confirmed == 1;
    }

    public function isSubscribed($author_id, $subscriber_id)
    {
        $res = Subscribe::where([
            ['author_id', '=', $author_id],
            ['subscriber_id', '=', $subscriber_id]
        ])->first();

        return (empty($res)) ? false : true;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\UserRepository;
use App\Repositories\ArticleRepository;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Requests\Users\UserProfileRequest;

/**
 * Class UsersController
 *
 * @package App\Http\Controllers
 */
class UsersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
    */
    public function __construct(UserRepository $users, ArticleRepository $articles)
    {
        $this->users = $users;
        $this->articles = $articles;
    }

    /**
     * Show all users
     *
     * @return $this
     */
    public function index()
    {
        $users = $this->users->getAll();
        return view('users.index')->with('users', $users);
    }

    /**
     * Show the user profile.
     *
     * @return \Illuminate\Http\Response
     */
    public function getSingleUser($id)
    {
        $user = $this->users->getOneUser($id);
        $articles = $this->articles->getAllByUser($id);

        return view('users.single')->with([
            'user' => $user,
            'articles' => $articles
        ]);
    }

    /**
     * @param UserProfileRequest $request
     *
     * Show user profile
     *
     * @return $this
     */
    public function profile(UserProfileRequest $request)
    {
        $user_id = Auth::user()->id;
        $user = $this->users->getOneUser($user_id);
        $articles = $this->articles->getAllByUser($user_id);

        return view('users.profile')->with([
            'user' => $user,
            'articles' => $articles
        ]);
    }

    /**
     * Subscribe for other users' updates
     *
     * @param Request $request
     * @return mixed
     */
    public function subscribe(Request $request)
    {
        $this->users->subscribe($request->all());

        return redirect()
            ->route('users.index')
            ->withFlashSuccess('You have been subscribed');
    }

}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Users</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                            @foreach($users as $user)
                                <div>
                                    <h4>{!! $user->name !!}</h4>
                                    <a href="/users/{!! $user->id !!}">Read more...</a>
                                </div>

                                <br><br>
                            @endforeach



                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{!! $user->name !!} profile</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <div>
                            <h3>{!! $user->name !!}</h3>
                            <a href="mailto:{!! $user->email !!}">{!! $user->email !!}</a>
                            <p>
                                Registration date: {!! date('d-m-Y', strtotime($user->created_at))  !!}
                            </p>
                        </div>

                        <hr>

                        <div>
                            <h3>Articles by {!! $user->name !!}</h3>
                            <h5>Total count: {!! count($user->articles) !!}</h5>
                            <br>
                            <a href="{{ route('articles.create') }}" title="Добавить"><span>Create article</span></a>
                            <br><br>
                            @foreach($articles as $article)
                                <div>
                                    <a href="/articles/{!! $article->slug !!}">{!! $article->title !!}</a>
                                    / <a href="{{ route('articles.edit', $article->slug) }}">Edit</a>
                                    <p>
                                        {!! $article->body !!}
                                    </p>
                                    <p>{!! date('d-m-Y', strtotime($article->created_at)) !!}</p>
                                </div>
                            @endforeach
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/single.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Users</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                            <div>
                                <h3>{!! $user->name !!}</h3>
                                <a href="mailto:{!! $user->email !!}">{!! $user->email !!}</a>
                                <p>
                                    Registration date: {!! date('d-m-Y', strtotime($user->created_at))  !!}
                                </p>
                                @if(app('auth')->user() !== null && app('auth')->user()->id !== $user->id)
                                    @if(app('auth')->user()->isSubscribed($user->id, app('auth')->user()->id))
                                        You have been subscribed
                                    @else
                                        <button data-route="{{ route('subscribe') }}" data-author="{{ $user->id }}" data-subscriber="{{ app('auth')->user()->id }}" id="subscribe_btn" class="btn btn-submit">
                                            Subscribe
                                        </button>
                                    @endif
                                @endif
                            </div>

                            <hr>

                            <div>
                                <h3>Articles by {!! $user->name !!}</h3>
                                <h5>Total count: {!! count($user->articles) !!}</h5>
                                <br><br>
                                @foreach($articles as $article)
                                    <div>
                                        <a href="/articles/{!! $article->slug !!}">{!! $article->title !!}</a>
                                        <p>
                                            {!! $article->body !!}
                                        </p>
                                        <p>{!! date('d-m-Y', strtotime($article->created_at)) !!}</p>
                                    </div>
                                @endforeach
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection